### ISSUE TITLE
direction detection out of PAS signal

### ISSUE THREAD

**Issue by stancecoke** [OpenSource-EBike-firmware/BMSBattery_S_controllers_firmware#20]
In torque-simulation mode the motor only should run, if you are turning the pedals in the right direction. If you are pedaling backwards, the motor should stop.
Some simple PAS do not have an internal direction detection. The direction information is hidden in the dutycycle of the PAS-pulses. e.g. a dutycycle >0.5 means pedaling forwards, dutycycle <0.5 means pedaling backwards. With the common LCD Displays you can set the proper dutycycle in the setup parameters.

**Comment by casainho** [comment]
Done.
